/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aula5.ArraysAtividade;

public class App {

    public static void main(String[] args) {
        menu Menu = new menu();
       Menu.menu();
    }
}